# -*- python -*-
# $Header$
# Authors: N.Omodei <nicola.omodei@pi.infn.it>
# Version: AncillaryDataRecon-01-00-02
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('AncillaryDataReconLib', depsOnly = 1)
AncillaryDataRecon = libEnv.SharedLibrary('AncillaryDataRecon', listFiles(['src/*.cxx']) + listFiles(['src/Dll/*.cxx']))

progEnv.Tool('AncillaryDataReconLib')
test_AncillaryDataRecon = progEnv.GaudiProgram('test_AncillaryDataRecon', ['src/test/AncillaryDataReconTest.cxx'] + listFiles(['src/*.cxx']), test = 1)

progEnv.Tool('registerObjects', package = 'AncillaryDataRecon', libraries = [AncillaryDataRecon], testApps = [test_AncillaryDataRecon], includes = listFiles(['AncillaryDataRecon/*.h']))
