# -*- python -*-
# $Header$
# Authors: N.Omodei <nicola.omodei@pi.infn.it>
# Version: AncillaryDataRecon-01-00-02
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('AncillaryDataReconLib', depsOnly = 1)
AncillaryDataRecon = libEnv.SharedLibrary('AncillaryDataRecon',
                                          listFiles(['src/*.cxx']) + listFiles(['src/Dll/*.cxx']))

progEnv.Tool('AncillaryDataReconLib')
test_AncillaryDataRecon = progEnv.Program('test_AncillaryDataRecon',
                                          ['src/test/AncillaryDataReconTest.cxx'] + listFiles(['src/*.cxx']))

progEnv.Tool('registerTargets', package = 'AncillaryDataRecon',
             libraryCxts = [[AncillaryDataRecon, libEnv]],
             testAppCxts = [[test_AncillaryDataRecon, progEnv]],
             includes = listFiles(['AncillaryDataRecon/*.h']))
