/*! acdPlots
\brief This routine accepts as input a histogram file generated via RootTreeAnalysis and generates
PHA plots for the ACDs and the XGTs.

  INPUT:  Path and filename of a histogram file generated by RootTreeAnalysis
          Path and filename of a new file to contain the output postscript file

  OUTPUT: Creates the postscript outputFile

  To RUN from the ROOT command line:
  .L acdPlots.cxx
  acdPlots("Histograms.root", "myNewPSFile.ps")

  */


void acdPlots(char *histfile, char *outputFile) {
    
    gROOT->Reset();
    /// Setup some global options for the plots
    /// This will setup our Statistics box for each plot
    gStyle->SetOptStat(1100);
    gStyle->SetStatH(0.3);   // height
    gStyle->SetStatW(0.4);   // width
    gStyle->SetStatX(1.1);
    
    gStyle->SetTitleColor(0); // Title box background Color
    gStyle->SetTitleH(0.11);  // Fraction of title box hight
    gStyle->SetTitleW(0.54);  // Fraction of title box width
    gStyle->SetTitleX(0.05);   // X position of the title box from left
    gStyle->SetTitleY(1.00);  // Y position of the title box from bottom

    // setup the canvas to contain the plots
    TCanvas *c1 = new TCanvas("c1","BFEM ACD",0,0,700,850);
    c1->Divide(4,5,0.005,0.02);

    // Set canvas title
    c1->SetTitle("BFEM ACD and XGT PHAs");
    c1->GetFrame()->SetFillColor(46);
    c1->SetFillColor(19);
    c1->SetBorderMode(28);
    
    // Setup the title of the plots
    TText *c1title = new TText(0.35,0.98,"BFEM ACD and XGT PHAs");
    c1title->SetTextSize(0.03);
    c1title->Draw();
    
    // open the histogram file
    TFile *histFile = new TFile(histfile); 
    
    TH1F *tile[17];
        
    // Read in the histograms from the file
    tile[0]  = (TH1F*) histFile->Get("ACDPHA000");
    tile[1]  = (TH1F*) histFile->Get("ACDPHA001"); 
    tile[2]  = (TH1F*) histFile->Get("ACDPHA010");
    tile[3]  = (TH1F*) histFile->Get("ACDPHA011");
    tile[4]  = (TH1F*) histFile->Get("ACDPHA100");
    tile[5]  = (TH1F*) histFile->Get("ACDPHA110");
    tile[6]  = (TH1F*) histFile->Get("ACDPHA200");
    tile[7]  = (TH1F*) histFile->Get("ACDPHA210");
    tile[8]  = (TH1F*) histFile->Get("ACDPHA300");
    tile[9]  = (TH1F*) histFile->Get("ACDPHA310");
    tile[10] = (TH1F*) histFile->Get("ACDPHA400");
    tile[11] = (TH1F*) histFile->Get("ACDPHA410");
    tile[12] = (TH1F*) histFile->Get("ACDPHA1000");  
    
    tile[13] = (TH1F*) histFile->Get("XGTPHA2000");
    tile[14] = (TH1F*) histFile->Get("XGTPHA2001");
    tile[15] = (TH1F*) histFile->Get("XGTPHA2010");
    tile[16] = (TH1F*) histFile->Get("XGTPHA2011");
    
    
    c1->SetLogy(1);
    
    // Now draw the histograms and setup the features of the plots
    int i;
    for(i=0;i<17;i++) {
        c1->cd(i+1);
        tile[i]->SetFillColor(46);
     //   tile[i]->SetLabelSize(0.07,"X");
      //  tile[i]->SetLabelSize(0.09,"Y");
        
        tile[i]->SetXTitle("PHA");
        tile[i]->SetYTitle("Nevents");
        tile[i]->SetTitleOffset(1.3,"X");
        tile[i]->SetTitleOffset(1.0,"Y");
        tile[i]->Draw();
    }


    // Print out the plots to a postscript file
    c1->Print(outputFile);
    
}















