# -*- python -*-
# $Header$
# Authors: Tracy Usher <usher@slac.stanford.edu>
# Version: GlastMS-02-00-00
Import('baseEnv')
Import('listFiles')
Import('packages')
#progEnv = baseEnv.Clone()
#libEnv = baseEnv.Clone()

#GlastMS = libEnv.StaticLibrary('GlastMS', listFiles(['src/*.cxx', 'src/*.cc']))

#progEnv.Tool('GlastMSLib')

#progEnv.Tool('registerTargets', package = 'GlastMS',
#             staticLibraryCxts = [[GlastMS, libEnv]],
#             includes = listFiles(['GlastMS/*.h']))




