# -*- python -*-
# $Header$
# Authors: Tracy Usher <usher@SLAC.Stanford.edu>
# Version: RootAnalysis-08-09-06
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()


progEnv.Tool('addLibrary', library = baseEnv['rootLibs'])
progEnv.Tool('addLibrary', library = baseEnv['rootGuiLibs'])
progEnv.Tool('facilitiesLib')
progEnv.Tool('commonRootDataLib')
progEnv.Tool('digiRootDataLib')
progEnv.Tool('mcRootDataLib')
progEnv.Tool('reconRootDataLib')
pruneTrees = progEnv.Program('pruneTrees', ['src/pruneTrees/PruneTree.cxx', 'src/pruneTrees/runTreeAnalysisChain.cxx'])
peelTrees = progEnv.Program('peelTrees', ['src/pruneTrees/PruneRunEvent.cxx', 'src/pruneTrees/runEventPeeler.cxx'])
mergeRootFiles = progEnv.Program('mergeRootFiles',
                                 ['src/utilityMacros/mergeRootFiles.cxx'])
test_RootAnalysis = progEnv.Program('test_RootAnalysis',
                                    ['src/test/runTreeAnalysis.cxx',
                                     'src/RootTreeAnalysis/RootTreeAnalysis.cxx'])

progEnv.Tool('registerTargets', package = 'RootAnalysis',
             testAppCxts = [[test_RootAnalysis, progEnv]], 
             binaryCxts = [[pruneTrees,progEnv], [peelTrees,progEnv],
                           [mergeRootFiles, progEnv]])
