# -*- python -*-
# $Header$
# Authors: Francesco Longo <Francesco.Longo@ts.infn.it>, Tracy Usher <usher@slac.stanford.edu>
# Version: G4HadronSim-03-00-00
Import('baseEnv')
Import('listFiles')
Import('packages')
#progEnv = baseEnv.Clone()
#libEnv = baseEnv.Clone()

##if baseEnv['PLATFORM'] != 'win32':
#G4HadronSim = libEnv.StaticLibrary('G4HadronSim',
#                                   listFiles(['src/Packaging/src/*.cc','src/LHEP/src/*.cc',
#                                              'src/LHEP_BERT/src/*.cc','src/LHEP_BIC/src/*.cc',
#                                              'src/LHEP_BIC/src/*.cc','src/QGSP/src/*.cc',
#                                              'src/QGSP_BERT/src/*.cc','src/QGSP_BIC/src/*.cc',
#                                              'src/QGSC/src/*.cc','src/QGSC_LEAD/src/*.cc',
#                                              'src/LC/src/*.cc','src/SE/src/*.cc']))

#progEnv.Tool('G4HadronSimLib')

#progEnv.Tool('registerTargets', package = 'G4HadronSim',
#             staticLibraryCxts = [[G4HadronSim, libEnv]], 
#             includes = listFiles(['G4HadronSim/*.hh'], recursive = 1))




