# -*- python -*-
# $Header$ 
# Authors: Riccardo Giannitrapani <riccardo@fisica.uniud.it>,Joanne Bogart <jrb@slac.stanford.edu>
# Version: rdbGui-01-13-00
import os
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('rdbGuiLib', depsOnly = 1)

if baseEnv['PLATFORM'] != 'win32':
	progEnv.AppendUnique(CCFLAGS = '-g')
	progEnv.AppendUnique(CCFLAGS = '-pipe')
	progEnv.AppendUnique(CCFLAGS = 'ansi')
	progEnv.AppendUnique(CCFLAGS = '-W')
	progEnv.AppendUnique(CCFLAGS = '-fPIC')
	progEnv.AppendUnique(CCFLAGS = '-shared')
	progEnv.AppendUnique(CPPDEFINES = 'linux')
	progEnv.AppendUnique(CPPDEFINES = 'unix')
	progEnv.AppendUnique(SHLINKFLAGS = '-Wl,-Bdynamic')

rdbGui = libEnv.SharedLibrary('rdbGui', listFiles(['src/*.cxx']) + listFiles(['src/Dll/*.cxx']))

progEnv.Tool('rdbGuiLib')
rdbGUI = progEnv.Program('rdbGUI', ['rdbFullGui.cxx','RdbGuiWindow.cxx', 
					'FXCheckList.cxx','TableColumnList.cxx',
					'QueryFrame.cxx', 'SQLBuffer.cxx','LogText.cxx', 
					'ResultTable.cxx','ConnectionDialog.cxx','InsertDialog.cxx',
					'StringWidget.cxx','ColWidgetFactory.cxx','DateWidget.cxx', 
					'EnumWidget.cxx', 'RealWidget.cxx', 'IntWidget.cxx', 'FXDate.cxx', 
					'FXDatePicker.cxx'])

progEnv.Tool('registerObjects', package = 'rdbGui', libraries = [rdbGui], 
	binaries = [rdbGUI], 
	includes = listFiles(['rdbGui/*.h']))
