# -*- python -*-
# $Header$ 
# Authors: Riccardo Giannitrapani <riccardo@fisica.uniud.it>,Joanne Bogart <jrb@slac.stanford.edu>
# Version: rdbGui-01-13-03
import os
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] != 'win32':
	progEnv.AppendUnique(CCFLAGS = '-g')
	progEnv.AppendUnique(CCFLAGS = '-pipe')
	progEnv.AppendUnique(CCFLAGS = '-ansi')
	progEnv.AppendUnique(CCFLAGS = '-W')
	progEnv.AppendUnique(CCFLAGS = '-fPIC')
	progEnv.AppendUnique(CCFLAGS = '-shared')
	progEnv.AppendUnique(CPPDEFINES = 'linux')
	progEnv.AppendUnique(CPPDEFINES = 'unix')
	progEnv.AppendUnique(SHLINKFLAGS = '-Wl,-Bdynamic')

progEnv.Tool('rdbModelLib')
progEnv.Tool('facilitiesLib')
progEnv.Tool('addLibrary', library = progEnv['foxLibs'])

rdbGUI = progEnv.Program('rdbGUI',
                         ['src/rdbFullGui.cxx','src/RdbGuiWindow.cxx', 
                          'src/FXCheckList.cxx','src/TableColumnList.cxx',
                          'src/QueryFrame.cxx', 'src/SQLBuffer.cxx',
                          'src/LogText.cxx', 'src/ResultTable.cxx',
                          'src/ConnectionDialog.cxx','src/InsertDialog.cxx',
                          'src/StringWidget.cxx','src/ColWidgetFactory.cxx',
                          'src/DateWidget.cxx', 'src/EnumWidget.cxx',
                          'src/RealWidget.cxx', 'src/IntWidget.cxx',
                          'src/FXDate.cxx', 'src/FXDatePicker.cxx'])

progEnv.Tool('registerTargets', package = 'rdbGui',
             binaryCxts = [[rdbGUI, progEnv]], 
             includes = listFiles(['rdbGui/*.h']))
