/**
 * CrCoordinateTransfer:
 *  This class calculate the geomagnetic latitude and longitude
 *  from geographic ones.
 */

//$Header$

#ifndef CrCoordinateTransfer_H
#define CrCoordinateTransfer_H

#include "math.h"

class CrCoordinateTransfer
{
public:
  CrCoordinateTransfer();
  ~CrCoordinateTransfer();

  // Calculate geomagnetic latitude and longitude from 
  // geographic ones
  // The input parameters (lat_deg and lon_deg) and return values are
  // given in degree, for consistency with a FluxSvc package.
  double geomagneticLatitude(double lat, double lon) const; // [degree]
  double geomagneticLongitude(double lat, double lon) const; // [degree]

private:

  // Determine the geomagnetic latitude or longitude by doing a linear interpolation
  // on a table generated by the GSFC program GEO_CGM.  Allowed range for
  // latitude is -30 to 30 degrees.  To calculate latitudes pass the array glats,
  // for longitudes pass the array glons.
  double interpolate(double lat, double lon, const double * array) const;

  // latitude and longitude of the geomagnetic north pole, in unit of degree
  double latitude_pole; // [deg]
  double longitude_pole; // [deg]

};

#endif CrCoordinateTransfer_H
