// Mainpage for doxygen

/** @mainpage package AnalysisNtuple

 @author Leon Rochester
 
 @section description Description

  The package contains a set of tools and an algorithm that runs them
  to produce a comprehensive ntuple of recon results. The tools,
  which can be invoked independently from the algorithm, also
  allow access to all of the calculated variables.

  The package name is a bit misleading, since the only the algorithm depends
  on NTupleWriterSvc, not the tools.

 @section AnalysisNtupleAlg AnalysisNtupleAlg

  This algorithm instantiates a set of tools, each dealing with a category of variables, 
  and sets up and calls the traverse() method of each tool with a pointer to a 
  visitor. Then it fills the ntuple with information from the visitor callback. 
  The code can handle floats and ints as well as doubles.

  It can also write out an ntuple using ntupleWriterSvc, but this capability is de-activated by 
  default, and is turned on only in the test program. The standard ntuple is produced by merit, using
  the information generated by this algorithm.

  The definition of the variables can be found in the "Related Pages" of the doxygen output.

  In debug mode, it exercises some other methods of the tools: getVal(), to return
  an individual value, and browse(), to print out a name and value.

  Since all the tools have the same abstract interface, the manipulation of these
  tools can be handled in a loop.

  AnalysisNtupleAlg also serves as the test routine for this package.
 

 @section tools Tools

  There are currently ten tools. 
  
  Eight are invoked to produce the standard merit ntuple:
  McValsTool, GltValsTool, CalValsTool, CalMipValsTool,
  TkrValsTool,  VtxValsTool, AcdValsTool and EvtValsTool.

  Two other tools are not part of the standard job, but may be invoked by adding their 
  names to the tools list: 
  TkrHitValsTool gives some addtional information about cluster counts, 
  and McAnalValsTool does an analysis of the simulated event; it requires 
  that various nonstandard packages have been run.
  
  EvtValsTool is special, in that it produces ntuple variables from the variables in 
  the other tools, using the getVal() method of those tools. These are generally needed 
  for the Gleam implementation of the classification trees.

  The common interface is IValsTool, which provides access to the values in each tool,
  and handles the interactions with the visitor through the class ValsVisitor.

  Each tool fills a list of variable names and pointers to the values they represent. 
  This is what allows the visitor to return names and values in a loop.

  Another method of each tool receives a call from the Gaudi IncidentSvc, to signal
  the beginning of a new event. This signal allows the tool to do its calculations 
  at most once for each event.

 @section jobOptions jobOptions

 @param AnalysisNtupleAlg.doNtuple
  Controls the generation of the ntuple. (Default is false.) This can be turned on for
  the test progream. For general use, the ntuple should be written out through the merit
  package.
  
 @param AnalysisNtupleAlg.tupleName 
  Sets the name of the ntuple. (Default is "".) Must be the one opened by NTupleWriteSvc,
  but there's no way for the code to find out what that is.  The name for
  a standard GLEAM job is "GLEAM".
 
 @param AnalysisNtupleAlg.tuple_name
  An alternate spelling, to match the one used by NTupleWriterSvc.

 @param AnalysisNtupleAlg.toolList
  A vector of strings that sets the list of tools requested. (Default is the 8 standard tools.) 
  Each string is the name
  of a tool with the "ValsTool" removed, so "TkrHitValsTool" becomes "TkrHit". This means that
  any tool written for the package should be named "BlahBlahValsTool". 
  
  <hr>
 @section vars Description of the variables
 Here are the <A HREF="./anatup_vars.html"> standard</A> variables, and here are the 
 <A HREF="./anatup_vars_optional.html"> optional</A> ones.

  <hr>
 @section notes Release Notes
  release.notes
 <hr>
 @section requirements requirements
 @verbinclude requirements
 <hr>

 */
