// $Id$
//
//  Original Author: Sawyer Gillespie
//                   hgillesp@u.washington.edu
//

#ifndef _H_GlastHitsEvt_SiStripHits_v0_
#define _H_GlastHitsEvt_SiStripHits_v0_

// includes
#include "Gaudi/Kernel/ContainedObject.h"
#include "GlastEvent/Hits/HitsBase.h"


    // declare the GAUDI class-id for this class
    extern const CLID&   CLID_SiStripHits;
    
    // class SiStripHits
    ///  This class represents the data associated with a single silicon
    //  strip hit in the tracker. 
    //
    /*!  In order for the container class to work properly as a Container, it 
     must support the following methods:
     -ACCESS
        - unsigned int  index () const  [ returns the strip-id]
        - float energy () const         [ returns the energy in GeV within the strip ]
        - bool  noise () const          [ returns whether or not strip was noise-generated ] 
     -SET 
        - index ( unsigned int )   [ sets the strip id ]
        - energy ( float )         [ sets the energy deposited ]
        - noise ( bool )           [ sets the noise flag ]
     -CLASS-WIDE (STATIC CLASS METHODS)
        - unsigned int undef_strip ()   [ returns a value taken as an 'undefined strip' ] 
    */
    template <class Container>
    class   SiStripHits : public ContainedObject,
                          public HitsBase <Container> {
    public:
        // default constructor
        SiStripHits () : HitsBase<Container> () {}
        
        // constructor
        SiStripHits (Container* s) : HitsBase<Container> (s) {}
        
        // destructor
        virtual ~SiStripHits () {}
        
        // GAUDI identification methods
        static const CLID&    classID ()  { return CLID_SiStripHits; }
        virtual const CLID&   clID ()     { return CLID_SiStripHits; }
        
        // *** Access Methods ***

        //! Access the strip id (from the left to right) for this particular strip
        unsigned int StripId () const { return hasObj() ? getContainer()->index() : Container::undef_strip(); }
                
        //! Access the energy deposited in this (negative indicates error)
        float Energy () const { return hasObj() ? getContainer()->energy() : -1.; }

        //! Was the strip generated by noise? (MC only)
        bool WasNoise () const { return hasObj() ? getContainer()->noise() : false; }

        //! An undefined strip value
        static unsigned int    UndefStrip () { return Container::undef_strip (); }

        // *** Set methods ***

        //! Set the strip id
        void    SetStripId ( unsigned int i ) { if (hasObj()) getContainer()->index(i); }

        //! Set the energy deposited
        void    SetEnergy ( float e ) { if (hasObj()) getContainer()->energy(e); }

        //! Set the noise flag
        void    SetNoise ( bool n ) { if (hasObj()) getContainer()->noise(n); }

    };



#endif // _H_GlastHitsEvt_SiStripHitsData_v0_