{
gROOT->Reset();
gROOT->LoadMacro("Layer.cxx+");
gROOT->LoadMacro("Recon.cxx+");
gROOT->LoadMacro("Tracker.cxx+");
gROOT->LoadMacro("Event.cxx+");
gROOT->LoadMacro("EventDisplay.cxx+");
gROOT->LoadMacro("Residual.cxx+");
//gROOT->LoadMacro("PlotMacros.C+");
}
