#!/bin/sh

geo=${1:?}

echo "// I cannot deduce what tower id should be put here."
echo "// Hence, you have to fill that in!"
echo
echo "tower -1"
echo
echo "//           shifts / um       rotations / mrad"
echo "//          x     y     z       x      y      z"

paste $geo geometry/TowerGeometryGleamv5r8.txt | gawk '{
    planeName = $1
   #  print "//", planeName
    viewName = substr(planeName, 1, 1)
    if ( viewName == "X" )
      view = 0
    else
      view = 1
    layer = substr(planeName, 2)
    face = ( layer + view ) % 2
    tray = layer + ( face + 1 ) % 2
    if ( tray == 0 || tray != tray0 ) print " "  
    if ( tray == 0 || tray != tray0 ) print "tray", tray
    tray0 = tray;
    printf "face %d", face
    printf "   %5.0f %5.0f %5.0f   %6.3f %6.3f %6.3f ", 1000*$4, 1000*$3, 1000*($2-$9), $7, $6, $5
    print "//", planeName
}'
