# -*- python -*-
# $Header$ 
# Authors: Johan Bregeon <johan.bregeon@pi.infn.it>
# Version: calibGenTRG-00-01-01
Import('baseEnv')
Import('listFiles')
Import('packages')

if baseEnv['PLATFORM'] != "win32":
  progEnv = baseEnv.Clone()
  libEnv = baseEnv.Clone()

  locIncs = listFiles(['calibGenTRG/*','src/*.h'])
  libEnv.Tool('addLinkDeps', package='calibGenTRG', toBuild='rootlib')
  calibGenTRGcint = libEnv.Rootcint('calibGenTRG/calibGenTRG_rootcint',
                                       ['calibGenTRG/afterglow.h',
                                        'calibGenTRG/mippeak.h',
                                        'calibGenTRG/RootTreeAnalysis.h',
                                        'calibGenTRG/takedata_mt.h',
                                        'calibGenTRG/treqACD.h',
                                        'calibGenTRG/treqCAL.h',
                                        'calibGenTRG/vetoeff.h',
                                        'src/fitTACK.h',
                                        'src/LangauFun.h',
                                        'src/egfun.h',
                                        'calibGenTRG/LinkDef.h'],
                                       includes = [''], localIncludes=locIncs,
                                       packageName='calibGenTRG')

  libEnv['rootcint_node'] = calibGenTRGcint
                                       
  calibGenTRG = libEnv.RootDynamicLibrary('calibGenTRG',
                                         listFiles(['src/*.cxx']) + ['calibGenTRG/calibGenTRG_rootcint.cxx'])

  # to fix code
  libEnv.AppendUnique(CXXFLAGS = ['-Wall']) 

  # to build dependencies in the library (for debug ?)
  libEnv.Tool('addLibrary', library = baseEnv['rootGuiLibs'])
  libEnv.Tool('addLibrary', library = baseEnv['rootLibs'])
  libEnv.Tool('addLibrary', library = baseEnv['clhepLibs'])
  libEnv.Tool('commonRootDataLib')
  libEnv.Tool('mcRootDataLib')
  libEnv.Tool('digiRootDataLib')
  libEnv.Tool('reconRootDataLib')
  libEnv.Tool('CalUtilLib')
  
  # Programs
  progEnv.Tool('calibGenTRGLib')

  progEnv.Tool('registerTargets', package = 'calibGenTRG',
               rootcintSharedCxts = [[calibGenTRG, libEnv]], 
               includes = listFiles(['calibGenTRG/*.h']))
