# Macro file for the initialization phase 
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/control/saveHistory
/run/verbose 2


# Here there are the particle settings
/gun/particle mu+
/gun/energy 100 MeV
/gun/position -90.0 0.0 0.0 cm
/gun/direction 1.0 0.0 0.0

# Here there are the material settings
/material/setMat Si
/material/setSizeY 50 cm
/material/setSizeZ 50 cm
/material/setThick 0.1 cm
/material/update

# Here we run the simulation
/run/beamOn 1000

exit
