# -*- python -*-
# $Header$
# Authors: N.Omodei <nicola.omodei@pi.infn.it>
# Version: AdfReader-00-03-05

Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', package='AdfReader', toBuild='component')
AdfReader = libEnv.SharedLibrary('AdfReader',
                                 listFiles(['src/Dll/*.cxx', 'src/*.cxx']))

progEnv.Tool('AdfReaderLib')

test_AdfReader=progEnv.Program('test_AdfReader',
                               ['src/test/AdfReaderTest.cxx'])
                               #['src/test/AdfReaderTest.cxx'] + listFiles(['src/*.cxx']))
progEnv.Tool('registerTargets', package = 'AdfReader',
             libraryCxts = [[AdfReader, libEnv]],
             testAppCxts = [[test_AdfReader, progEnv]],
             includes = listFiles(['AdfReader/*.h']),
             jo=['src/jobOptions.txt', 'src/test/jobOptions.txt'])

