#ifndef HepEventServer_idl
#define HepEventServer_idl

//
// Author: Joseph Perl
//
// $Id$
//

interface HepEventServer {
    string attach(in string clientDesc);
    oneway void release();
    string setEvent(in string eventID);
    long getNumberOfEvents();
    string getEventTitle();
    any getEventData(in string dataFormat);
};

#endif
