#ifndef HepEventServer_idl
#define HepEventServer_idl

//
// Author: Joseph Perl
//
// $Id$
//

#include "HepRep.idl"

interface HepEventServer {
    string attach(in string clientDesc);
    oneway void release();
    string setEvent(in string eventID);
    long getNumberOfEvents();
    string getEventTitle();
    HepRep getEventData(in string dataFormat);
};

#endif
